server:
  port: 8084

spring:
  application:
    name: log-radar
  datasource:
    url: jdbc:mysql://localhost:3306/log_radar_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  elasticsearch:
    rest:
      uris: http://localhost:9200
  aop:
    auto: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: log-radar-producer
  consumer:
    pull-batch-size: 32
logging:
  level:
    org.apache.rocketmq: WARN
    com.alibaba.otter.canal: WARN

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
knife4j:
  enable: true

